# SPDX-FileCopyrightText: 2023 DESY and the Constellation authors
# SPDX-License-Identifier: EUPL-1.2

stages:
    - formatting

.format:
    stage: formatting
    needs: []
    dependencies: []

fmt:format:
    extends: .format
    image:
        name: registry.cern.ch/docker.io/ubuntu:latest
    script:
        # FIXME we need a proper base image...
        - apt-get update && apt-get -y install git meson clang-format ninja-build
        - meson setup build
        - ninja -C build clang-format

fmt:reuse:
    extends: .format
    image:
        name: registry.cern.ch/docker.io/fsfe/reuse:latest
        entrypoint: [""]
    script:
        - reuse lint
