# SPDX-FileCopyrightText: 2023 DESY and the Constellation authors
# SPDX-License-Identifier: EUPL-1.2

stages:
    - formatting

fmt:format:
    script:
        - meson setup build
        - ninja -C build clang-format

fmt:reuse:
    image:
        name: registry.cern.ch/docker.io/fsfe/reuse:latest
        entrypoint: [""]
    stage: formatting
    needs: []
    dependencies: []
    script:
        - reuse lint
