# SPDX-FileCopyrightText: 2023 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

- id: reuse
  name: reuse
  language: python
  entry: reuse
  args: ["lint"]
  pass_filenames: false
  description:
    "Linting REUSE Specification compliance"
