# SPDX-FileCopyrightText: 2023 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

# This is an example of the configuration layout in TOML-file-format.
# Used for testing configuration setup

[constellation]
# General system settings for network
name = "myconstellation"

[constellation.keithley]
# Class-specific system settings for network
importance = "low"

[constellation.keithley.powersupply2]
# Device-specific system settings for network
importance = "essential"
start_after = "powersupply1"


[controller]
# General system settings for controller
constellation_name = "myconstellation"
show_extra_stuff = true
scan = "something"


[satellites]
# General system settings for satellites
verbosity = "DEBUG"

[satellites.keithley]
# Class-specific system settings for satellites
current_limit = 5

[satellites.keithley.powersupply1]
# Device-specific system settings for satellites
voltage = 5000

[satellites.keithley.powersupply2]
# Device-specific system settings for satelli
voltage = 3000
