[constellation]
name = "myconstellation"

[constellation.keithley]
importance = "low"

[constellation.keithley.powersupply2]
importance = "essential"
start_after = "powersupply1"


[controller]
constellation_name = "myconstellation"
show_extra_stuff = true
scan = "something"


[satellites]

verbosity = "DEBUG"

[satellites.keithley]
current_limit = 5

[satellites.keithley.powersupply1]
voltage = 5000

[satellites.keithley.powersupply2]
voltage = 3000
