# SPDX-FileCopyrightText: 2023 DESY and the Constellation authors
# SPDX-License-Identifier: CC0-1.0

# This is an example of the configuration layout in TOML-file-format.
# Used for testing configuration setup

# The layers of a configuration file should consist of:
# [Category] -> [Class] -> [Device]

[constellation]
# General system settings for network
name = "exampleconstellation"

[satellites]
# General system settings for satellites
verbosity = "DEBUG"

[satellites.examplesat]
# Class-specific system settings for satellites
voltage = 5
ampere = 2
sample_period = 0.8
